[build]
command = "npm run update && npm run build && npm run check"
publish = "public"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[[headers]]
for = "/*"
  [headers.values]
  X-Frame-Options = "SAMEORIGIN"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
