[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "upgrade-insecure-requests"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[build.processing.html]
  pretty_urls = true

[build.environment]
  AFFIL_TAG = "kayce25-20"

[[scheduled.functions]]
  path = "functions/refresh_catalog.ts"
  schedule = "@daily"
