[build]
command = "python -m giftgrab.cli update && python -m giftgrab.cli roundups --limit 15"
publish = "public"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[[headers]]
for = "/*"
  [headers.values]
  X-Frame-Options = "SAMEORIGIN"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
